name: generate albums page

on:
  push:
    branches:
      - main  # Adjust to the branch used for GitHub Pages

jobs:
  generate-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug directory structure
      run: |
        ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate album page
      run: |
        python scripts/generate_albums_page.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pages/albums.html
        git commit -m "Update albums.html [skip ci]" || echo "No changes to commit"
        git push
